name: CI Pipeline

on:
  pull_request:
    branches:
      - dev
      - stage
      - prod

jobs:
  ci:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '15.5.1'  # Use the node version your project requires

      # Install dependencies
      - name: Install dependencies
        run: npm install

      # Run ESLint (Linter)
      - name: Run ESLint
        run: npm run lint

      # Run Prettier (Formatter)
      - name: run prettier (auto-fix)
        run: npm prettier --write .

      # Run tests with Jest
      - name: Run Jest Tests
        run: CI=true npm run test

      # Build the application
      - name: Build application
        run: npm run build

      - name: configure aws credentials
        uses: aws-actions/configure-aws-credentials@v3
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: ${{ secrets.AWS_REGION}}

      - name: deploy to s3 based on the target branch
        run: |
          if [ "${{ github.base_ref }}" == "dev" ]; then
            aws s3 sync ./build s3://cicd-devops-dev/ --delete
          elif [ "${{ github.base_ref }}" == "stage" ]; then
            aws s3 sync ./build s3://cicd-devops-staging/ --delete
          elif [ "${{ github.base_ref }}" == "prod" ]; then
            aws s3 sync ./build s3://cicd-devops-prod/ --delete
          else
            echo "Branch not configured for s3 deployment"
            exit 1
          fi  
